---
name: Auto Merge Dev to main
on:
  push:
    branches: [dev]
jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Merge 'dev' into 'main'
        run: |
          git checkout main
          git merge dev --no-ff -m "Auto-merge from dev after successful merge into dev branch"
      - name: Push Changes to 'main'
        run: git push origin main
