---
name: Lua Linter PR Check
on:
  pull_request:
    branches: [dev]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: 🔎 Run Luacheck Linter
        uses: lunarmodules/luacheck@v1
        with:
          files: '*.lua'
      - name: Run Yamllint Check
        run: yamllint .
