jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: 📝 Run Yamllint Check
        uses: actions/yamllint@v1 
        with:
          file_or_dir: '.' 
